import type { Severity, VehicleType } from "./types";

export interface FaultDefinition {
  id: string;
  label: string;
  /** keyword -> weight. Includes Hinglish / transliterated terms drivers actually type. */
  keywords: Record<string, number>;
  severity: Severity;
  roadsideFixable: boolean;
  fixMinutes: number;
  costRange: [number, number];
  skills: string[];
  tools: string[];
  parts: string[];
  vehicleTypes: VehicleType[] | "all";
  safetyAdvice: string[];
}

const COMMON_NIGHT_ADVICE = [
  "Switch on hazard lights immediately and keep parking lights on.",
  "Move every passenger OUT of the vehicle and behind the crash barrier, never onto the road side.",
  "Place a warning triangle or any reflective object 50-100 m behind the vehicle.",
];

export const FAULTS: FaultDefinition[] = [
  {
    id: "flat_tyre",
    label: "Flat tyre / puncture",
    keywords: {
      puncture: 6, punchar: 6, flat: 5, tyre: 4, tire: 4, deflated: 4,
      air: 2, "pressure": 2, nail: 3, wheel: 2, "pancher": 6, rim: 2,
    },
    severity: "medium",
    roadsideFixable: true,
    fixMinutes: 25,
    costRange: [250, 700],
    skills: ["tyre"],
    tools: ["Hydraulic jack", "Wheel spanner", "Puncture kit", "Foot pump / mini compressor"],
    parts: ["tube-patch-kit", "valve-stem"],
    vehicleTypes: "all",
    safetyAdvice: [
      ...COMMON_NIGHT_ADVICE,
      "Do not attempt to jack the car on soft shoulder or a slope.",
    ],
  },
  {
    id: "tyre_burst",
    label: "Tyre burst / sidewall damage",
    keywords: {
      burst: 7, blast: 6, blew: 6, exploded: 5, "phat": 6, shredded: 5,
      sidewall: 5, tyre: 3, tire: 3, bang: 3, loud: 2,
    },
    severity: "high",
    roadsideFixable: true,
    fixMinutes: 35,
    costRange: [1800, 7500],
    skills: ["tyre"],
    tools: ["Hydraulic jack", "Wheel spanner", "Torque wrench"],
    parts: ["tyre-replacement", "wheel-nut"],
    vehicleTypes: "all",
    safetyAdvice: [
      ...COMMON_NIGHT_ADVICE,
      "A burst tyre often damages the wheel arch. Do not drive even a short distance on the rim.",
    ],
  },
  {
    id: "battery_dead",
    label: "Dead battery / no crank",
    keywords: {
      battery: 7, dead: 4, "won't start": 6, "not starting": 6, crank: 5,
      click: 4, clicking: 5, "no power": 5, lights: 2, dim: 3, jump: 4,
      "band ho": 4, terminal: 3, "self nahi": 4,
    },
    severity: "medium",
    roadsideFixable: true,
    fixMinutes: 20,
    costRange: [300, 5500],
    skills: ["electrical", "battery"],
    tools: ["Jump starter pack", "Jumper cables", "Multimeter", "Terminal brush"],
    parts: ["battery-12v", "battery-terminal"],
    vehicleTypes: "all",
    safetyAdvice: [
      ...COMMON_NIGHT_ADVICE,
      "Turn off AC, music and headlights to conserve whatever charge is left.",
    ],
  },
  {
    id: "alternator_fail",
    label: "Alternator / charging system failure",
    keywords: {
      alternator: 8, charging: 6, "battery light": 6, dynamo: 5,
      "drained while driving": 6, "died while driving": 5, dimming: 4, flicker: 4,
    },
    severity: "high",
    roadsideFixable: false,
    fixMinutes: 90,
    costRange: [3500, 12000],
    skills: ["electrical", "engine"],
    tools: ["Multimeter", "Socket set", "Belt tensioner tool"],
    parts: ["alternator", "drive-belt"],
    vehicleTypes: "all",
    safetyAdvice: [
      ...COMMON_NIGHT_ADVICE,
      "The battery will die within minutes. Keep one phone fully off as a reserve.",
    ],
  },
  {
    id: "overheating",
    label: "Engine overheating",
    keywords: {
      overheat: 8, heating: 6, steam: 6, smoke: 4, "temperature": 6,
      hot: 4, coolant: 6, radiator: 6, boiling: 5, "red mark": 4, "garam": 4,
    },
    severity: "high",
    roadsideFixable: true,
    fixMinutes: 45,
    costRange: [500, 4000],
    skills: ["engine", "cooling"],
    tools: ["Coolant funnel", "Pressure tester", "Hose clamp pliers"],
    parts: ["coolant-1l", "radiator-hose", "radiator-cap"],
    vehicleTypes: "all",
    safetyAdvice: [
      ...COMMON_NIGHT_ADVICE,
      "DO NOT open the radiator cap. Pressurised steam causes severe burns. Wait 30 minutes.",
      "Switch the engine off now. Every extra minute risks a seized engine.",
    ],
  },
  {
    id: "fuel_empty",
    label: "Out of fuel",
    keywords: {
      fuel: 6, petrol: 7, diesel: 7, empty: 5, "no fuel": 8, tank: 4,
      reserve: 4, "fuel over": 7, gas: 4, "khatam": 4,
    },
    severity: "low",
    roadsideFixable: true,
    fixMinutes: 30,
    costRange: [200, 1500],
    skills: ["fuel"],
    tools: ["Jerry can (5 L)", "Funnel"],
    parts: ["fuel-5l"],
    vehicleTypes: "all",
    safetyAdvice: [
      ...COMMON_NIGHT_ADVICE,
      "Do not keep cranking the starter. A dry fuel pump can burn out.",
    ],
  },
  {
    id: "fan_belt",
    label: "Fan belt / serpentine belt snapped",
    keywords: {
      belt: 7, "fan belt": 8, serpentine: 7, squeal: 5, squealing: 5,
      screech: 5, snapped: 5, whining: 3,
    },
    severity: "high",
    roadsideFixable: true,
    fixMinutes: 50,
    costRange: [800, 3000],
    skills: ["engine"],
    tools: ["Belt tensioner tool", "Socket set", "Torch"],
    parts: ["drive-belt", "tensioner-pulley"],
    vehicleTypes: ["car", "suv", "truck"],
    safetyAdvice: [
      ...COMMON_NIGHT_ADVICE,
      "Without the belt the water pump has stopped. Do not restart the engine.",
    ],
  },
  {
    id: "brake_failure",
    label: "Brake failure / brake fluid loss",
    keywords: {
      brake: 8, brakes: 8, "no brakes": 10, spongy: 6, "pedal soft": 6,
      grinding: 5, "brake fluid": 8, leak: 3, "not stopping": 7,
    },
    severity: "critical",
    roadsideFixable: false,
    fixMinutes: 120,
    costRange: [1500, 9000],
    skills: ["brakes", "hydraulics"],
    tools: ["Brake bleeding kit", "Jack", "Spanner set"],
    parts: ["brake-fluid", "brake-pad-set", "brake-hose"],
    vehicleTypes: "all",
    safetyAdvice: [
      "Do not drive this vehicle under any circumstances, not even to the next exit.",
      ...COMMON_NIGHT_ADVICE,
    ],
  },
  {
    id: "clutch_failure",
    label: "Clutch failure",
    keywords: {
      clutch: 8, "gear not": 6, "gears not": 6, slipping: 5, burning: 3,
      "smell burning": 4, "cannot shift": 6, "won't go into gear": 7,
    },
    severity: "high",
    roadsideFixable: false,
    fixMinutes: 150,
    costRange: [4000, 18000],
    skills: ["transmission"],
    tools: ["Trolley jack", "Transmission jack", "Socket set"],
    parts: ["clutch-plate", "clutch-cable", "clutch-fluid"],
    vehicleTypes: ["car", "suv", "truck", "auto"],
    safetyAdvice: [...COMMON_NIGHT_ADVICE],
  },
  {
    id: "starter_motor",
    label: "Starter motor failure",
    keywords: {
      starter: 8, "self start": 6, "self not": 6, whirring: 5,
      "engine not turning": 6, solenoid: 6, "grinding on start": 6,
    },
    severity: "medium",
    roadsideFixable: true,
    fixMinutes: 60,
    costRange: [1200, 6000],
    skills: ["electrical", "engine"],
    tools: ["Socket set", "Multimeter", "Hammer (bench tap)"],
    parts: ["starter-motor", "solenoid"],
    vehicleTypes: "all",
    safetyAdvice: [...COMMON_NIGHT_ADVICE],
  },
  {
    id: "spark_plug",
    label: "Spark plug / ignition misfire",
    keywords: {
      spark: 7, plug: 6, misfire: 7, jerking: 5, sputtering: 6, stalling: 5,
      "engine shaking": 5, backfire: 5, coil: 5,
    },
    severity: "medium",
    roadsideFixable: true,
    fixMinutes: 35,
    costRange: [400, 2500],
    skills: ["engine", "electrical"],
    tools: ["Spark plug socket", "Gap gauge", "Torch"],
    parts: ["spark-plug", "ignition-coil"],
    vehicleTypes: "all",
    safetyAdvice: [...COMMON_NIGHT_ADVICE],
  },
  {
    id: "radiator_leak",
    label: "Radiator / coolant hose leak",
    keywords: {
      "coolant leak": 8, "water leak": 6, radiator: 6, hose: 6, dripping: 5,
      "green liquid": 6, puddle: 5, "leaking under": 6,
    },
    severity: "high",
    roadsideFixable: true,
    fixMinutes: 55,
    costRange: [600, 5000],
    skills: ["cooling", "engine"],
    tools: ["Hose clamp pliers", "Sealant", "Coolant funnel"],
    parts: ["radiator-hose", "coolant-1l", "hose-clamp"],
    vehicleTypes: "all",
    safetyAdvice: [
      ...COMMON_NIGHT_ADVICE,
      "Coolant is toxic. Keep children and animals away from the puddle.",
    ],
  },
  {
    id: "chain_snap",
    label: "Drive chain snapped / slipped",
    keywords: {
      chain: 8, sprocket: 7, "chain broke": 9, "chain off": 8, loose: 3,
      rattling: 4,
    },
    severity: "medium",
    roadsideFixable: true,
    fixMinutes: 30,
    costRange: [300, 2200],
    skills: ["two-wheeler"],
    tools: ["Chain breaker tool", "Spanner set", "Chain lube"],
    parts: ["chain-link", "drive-chain", "sprocket"],
    vehicleTypes: ["bike"],
    safetyAdvice: [...COMMON_NIGHT_ADVICE],
  },
  {
    id: "electrical_fuse",
    label: "Blown fuse / wiring fault",
    keywords: {
      fuse: 8, wiring: 6, short: 5, "no lights": 6, "headlight not": 7,
      indicator: 4, "electrical": 5, spark: 3, "burning smell": 4,
    },
    severity: "medium",
    roadsideFixable: true,
    fixMinutes: 30,
    costRange: [150, 2000],
    skills: ["electrical"],
    tools: ["Fuse puller", "Multimeter", "Insulation tape", "Torch"],
    parts: ["fuse-assorted", "relay", "wire-loom"],
    vehicleTypes: "all",
    safetyAdvice: [
      ...COMMON_NIGHT_ADVICE,
      "If you smell burning plastic, disconnect the battery negative terminal now.",
    ],
  },
  {
    id: "key_lockout",
    label: "Keys locked in / lost key",
    keywords: {
      locked: 8, "keys inside": 9, "lost key": 9, immobiliser: 6,
      "key not working": 7, remote: 4, "cannot open": 6,
    },
    severity: "low",
    roadsideFixable: true,
    fixMinutes: 35,
    costRange: [500, 3500],
    skills: ["locksmith"],
    tools: ["Lockout kit", "Wedge", "Long reach tool"],
    parts: [],
    vehicleTypes: "all",
    safetyAdvice: [
      "If a child or pet is locked inside, call 112 immediately. Do not wait for a mechanic.",
      ...COMMON_NIGHT_ADVICE,
    ],
  },
  {
    id: "engine_seize",
    label: "Suspected engine seizure",
    keywords: {
      seized: 9, "knocking": 7, "loud knock": 8, "engine locked": 8,
      "white smoke": 6, "blue smoke": 6, "oil light": 6, "no oil": 7,
    },
    severity: "critical",
    roadsideFixable: false,
    fixMinutes: 240,
    costRange: [15000, 90000],
    skills: ["engine"],
    tools: ["Diagnostic scanner", "Compression tester"],
    parts: [],
    vehicleTypes: "all",
    safetyAdvice: [
      "Do not attempt to restart. Each crank makes the damage worse and more expensive.",
      ...COMMON_NIGHT_ADVICE,
    ],
  },
  {
    id: "suspension",
    label: "Suspension / ball joint / axle damage",
    keywords: {
      suspension: 7, shocker: 7, "ball joint": 8, axle: 7, pothole: 5,
      clunk: 5, "steering pulling": 6, bump: 3, wobble: 5, "wheel bent": 7,
    },
    severity: "high",
    roadsideFixable: false,
    fixMinutes: 120,
    costRange: [2000, 15000],
    skills: ["suspension"],
    tools: ["Trolley jack", "Ball joint separator", "Spring compressor"],
    parts: ["ball-joint", "shock-absorber", "tie-rod"],
    vehicleTypes: "all",
    safetyAdvice: [...COMMON_NIGHT_ADVICE],
  },
  {
    id: "accident_damage",
    label: "Collision / accident damage",
    keywords: {
      accident: 9, crash: 8, collision: 8, hit: 5, injured: 8, blood: 8,
      rollover: 9, ditch: 6, "hit a": 6,
    },
    severity: "critical",
    roadsideFixable: false,
    fixMinutes: 180,
    costRange: [5000, 100000],
    skills: ["recovery", "towing"],
    tools: ["Recovery straps", "Winch", "First aid kit"],
    parts: [],
    vehicleTypes: "all",
    safetyAdvice: [
      "If anyone is hurt, call 108 (ambulance) or 112 right now, before anything else.",
      "Do not move an injured person unless the vehicle is on fire.",
      ...COMMON_NIGHT_ADVICE,
    ],
  },
];

/** Human-readable names for part SKUs used across triage and inventory. */
export const PART_NAMES: Record<string, string> = {
  "tube-patch-kit": "Tube patch kit",
  "valve-stem": "Valve stem",
  "tyre-replacement": "Replacement tyre",
  "wheel-nut": "Wheel nuts",
  "battery-12v": "12V battery",
  "battery-terminal": "Battery terminal",
  alternator: "Alternator",
  "drive-belt": "Drive belt",
  "tensioner-pulley": "Tensioner pulley",
  "coolant-1l": "Coolant (1 L)",
  "radiator-hose": "Radiator hose",
  "radiator-cap": "Radiator cap",
  "hose-clamp": "Hose clamp",
  "fuel-5l": "Fuel (5 L can)",
  "brake-fluid": "Brake fluid",
  "brake-pad-set": "Brake pad set",
  "brake-hose": "Brake hose",
  "clutch-plate": "Clutch plate",
  "clutch-cable": "Clutch cable",
  "clutch-fluid": "Clutch fluid",
  "starter-motor": "Starter motor",
  solenoid: "Starter solenoid",
  "spark-plug": "Spark plug",
  "ignition-coil": "Ignition coil",
  "chain-link": "Chain master link",
  "drive-chain": "Drive chain",
  sprocket: "Sprocket",
  "fuse-assorted": "Assorted fuses",
  relay: "Relay",
  "wire-loom": "Wire loom",
  "ball-joint": "Ball joint",
  "shock-absorber": "Shock absorber",
  "tie-rod": "Tie rod",
};

export function partName(sku: string): string {
  return PART_NAMES[sku] ?? sku;
}
